### ISSUE TITLE
Create user story schemes

### ISSUE THREAD

**Issue by juliusrueckin** [hpi-swa-teaching/StatisticsWorkbench#1]
**Priority**: Highest/ High/ Medium/ Low
**Status**: to do/ in progress/ to review/ done

**AS A** developer
**I WANT TO** know my specific tasks in a user story format
**IN ORDER TO** get things done

**ACCEPTANCE CRITERIA** 
- [ ] all user stories are written in this specific standard format

**Comment by Julius97** [comment]
document changes/ problems/ questions in comments below
