### ISSUE TITLE
Assign names to pie charts - 3

### ISSUE THREAD

**Issue by bisbaldi** [hpi-swa-teaching/StatisticsWorkbench#11]
**Priority**: Low
**Status**: to review

**I WANT TO** assign segment names to my pie chart.
**IN ORDER TO** make the diagram mire descriptive.

**ACCEPTANCE CRITERIA** 
- [x] Name is assigned correctly
- [x] Text doesn't overlap

**Comment by bisbaldi** [comment]
geändert in PieKey

**Comment by ekrebs5** [comment]
Problem: funktioniert nicht Graphen-übergreifend

**Comment by ekrebs5** [comment]
verschoben auf nach UI Erstellung
neu schätzen!

**Comment by Kenneth-Schroeder** [comment]
partly moved to #74
