### ISSUE TITLE
Mean/Median/Mode - 2

### ISSUE THREAD

**Issue by marcfreiheit** [hpi-swa-teaching/StatisticsWorkbench#19]
**EPIC**: #15
**Priority**: Low
**Status**: to do

**I WANT TO** calculate mean, median and mode for each and both dimensions.

**ACCEPTANCE CRITERIA** 
- [x] mean
- [x] median
- [x] mode

**Comment by Kenneth-Schroeder** [comment]
fixed in ~ 2
additionally added coutingSort for mode and testcases.

**Comment by ekrebs5** [comment]
abgenommen
