### ISSUE TITLE
Maximal and minimal local derivation - 2

### ISSUE THREAD

**Issue by marcfreiheit** [hpi-swa-teaching/StatisticsWorkbench#23]
**EPIC**: #15 
**Priority**: Low
**Status**: to do

**I WANT TO** calculate the maximal and minimal local derivation.
**IN ORDER TO** get most interesting changes in data.

**ACCEPTANCE CRITERIA** 
- [x] tba

**Comment by Kenneth-Schroeder** [comment]
fixed in ~ 2

**Comment by ekrebs5** [comment]
abgenommen
