### ISSUE TITLE
Create bar chart from collection - 3

### ISSUE THREAD

**Issue by juliusrueckin** [hpi-swa-teaching/StatisticsWorkbench#3]
**Priority**: High
**Status**: to review

**I WANT TO** visualize a collection of numbers as a 2-d bar chart. The bars should have a width and a color.

**ACCEPTANCE CRITERIA** 
- [x] Numbers should be read from a collection
- [x] Y-axis adjusts to number range of collection
- [x] Y-axis step size is set to 1 by default
- [x] Width of the bars is adjustable
- [x] Update method should read data from collection and update diagram if necessary
- [x] Graph visualizes collection correctly

**Comment by Kenneth-Schroeder** [comment]
überprüfen, ob Balkenbreite in window und world geht

**Comment by ekrebs5** [comment]
abgenommen
