### ISSUE TITLE
Extract workflow graph from workspace script

### ISSUE THREAD

**Issue by juliusrueckin** [hpi-swa-teaching/StatisticsWorkbench#30]
**EPIC**: #17 
**Priority**: Medium
**Status**: to do

**I WANT TO** build a workflow graph from user defined step operations.
**IN ORDER TO** have a generalized workflow representation.

**ACCEPTANCE CRITERIA** 
- [ ] Treat operations as DAG
- [ ] Build graph for serialized worfklow and support split operations at each node
- [ ] Use explorer as an GUI and show executed operations in valid useful structure
- [ ] Graph must support user operations as defined in attached image

**Comment by bisbaldi** [comment]
![workflow](https://user-images.githubusercontent.com/27973778/28744861-df187296-746a-11e7-8903-b431ee8c07a1.jpg)
