### ISSUE TITLE
Organize User Stories - 1

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/StatisticsWorkbench#34]
As customer I want all user stories in compiled in one place so I can have an overview of all of them during the meetings.

Aceptance Criteria:
- [X] update old stories
- [x] close old won't-fix stories
- [x] add new stories
- [x] estimate all open stories

**Comment by Kenneth-Schroeder** [comment]
Ich finde #15 bis #23 (die nicht als "wontfix" markiert sind) gar nicht schlecht. einige davon können wir vielleicht übernehmen...
