### ISSUE TITLE
Bar Chart - Bar Position

### ISSUE THREAD

**Issue by LegendDarkness97** [hpi-swa-teaching/StatisticsWorkbench#44]
Currently bars are positioned to their value (x-axis) with their right border. Changing this so that a bar is positioned so that its middle corresponds with its value (x-axis) would be more in line with other software.

**Comment by LegendDarkness97** [comment]
This would distort the visual representation of the x-axis.

**Comment by ekrebs5** [comment]
fixed as part of #3
