### ISSUE TITLE
Assign names to bars - 8

### ISSUE THREAD

**Issue by juliusrueckin** [hpi-swa-teaching/StatisticsWorkbench#5]
**Priority**: Medium
**Status**: to review

**I WANT TO** have a name for my bars
**IN ORDER TO** make the diagram more descriptive

**ACCEPTANCE CRITERIA** 
- [ ] Name equals key
- [ ] Text doesn't overlap
- [ ] Text rotates if necessary

**Comment by ekrebs5** [comment]
verschoben auf nach UI Erstellung
neu schätzen!

**Comment by ekrebs5** [comment]
to clarify:
additional label value to points
only has to be used by bar chart

**Comment by ekrebs5** [comment]
accepted
