### ISSUE TITLE
Welche neuen User Stories habt ihr für Sprint 3?

### ISSUE THREAD

**Issue by SanJSp** [hpi-swa-teaching/StatisticsWorkbench#88]
Bitte einfach mal die User Stories kommentieren. Jeder mal 2 Stück

**Comment by SanJSp** [comment]
Als Nutzer möchte ich gerne, dass die Labels des Balkendiagramms an der x-Achse angezeigt werden können. Momentan werden diese auf den Balken dargestellt.

**Comment by SanJSp** [comment]
Als Nutzer möchte ich in einem Balkendiagramm mehrere Werte pro x Wert darstellen können z.B Frauen und Männer in Jahrgang x. Das heißt ich möchte mehrere Balken am selben x Wert.

**Comment by SanJSp** [comment]
Als Nutzer möchte ich die Labels meiner Daten in einem Kreisdiagramm dargestellt bekommen.

Bezeiht sich auf #74

**Comment by Panicmod-e** [comment]
Als Nutzer möchte ich die Werte meiner Daten in einem Kreisdiagramm dargestellt bekommen können.

**Comment by Panicmod-e** [comment]
Als Nutzer möchte ich die Größe der Kreisdiagramme nach Erzeugung ändern können, so dass die Diagramme korrekt skaliert werden.

**Comment by Iyadkrayem** [comment]
Als Nutzer möchte ich, dass meine Daten besser repräsentiert werden, wenn die kleine Nachkommazahlen enthalten.

**Comment by Iyadkrayem** [comment]
Als Nutzer möchte ich, dass meine Daten besser repräsentiert werden, wenn die kleine Nachkommazahlen enthalten.

**Comment by Iyadkrayem** [comment]
Als Nutzer möchte ich, dass meine Diagramme ab einen bestimmten Punkt nicht mehr verkleinert werden.

**Comment by Iyadkrayem** [comment]
Als Nutzer möchte ich, dass die Pie-Charts bei negativen Werten als Eingaben eine Fehlermeldung zeigen und nicht eine sinnlose Repräsentation.

**Comment by Iyadkrayem** [comment]
Als Nutzer möchte ich, dass die Bars bei Bar-Chart nicht mit der Y-Axe kollidieren

**Comment by jostmorgenstern** [comment]
**kumulative Liniendiagramme**
Als Nutzer möchte ich kumulative Liniendiagramme zeichnen können, also Liniendiagramme mit mehreren Datensätzen deren Werte addiert dargestellt werden
**Beispiel:** https://images.app.goo.gl/gJAR7PQJvMb6XZzq6

**Comment by jonathankreidler** [comment]
Wurden alle als Notizen ins [User Story Kanban Board](https://github.com/hpi-swa-teaching/StatisticsWorkbench/projects/1) aufgenommen
