### ISSUE TITLE
Create labels for axis - 13

### ISSUE THREAD

**Issue by bisbaldi** [hpi-swa-teaching/StatisticsWorkbench#9]
**Priority**: Low
**Status**: in progress

**I WANT TO** have the possibility to label the axis.
**IN ORDER TO** have more structure.

**ACCEPTANCE CRITERIA** 
- [x] Correct mapping from label to axis
- [ ]  Labels do not overlap other GUI elements
- [x] Label text can be changed

**Comment by ekrebs5** [comment]
verschoben auf nach UI Erstellung
neu schätzen!

**Comment by ekrebs5** [comment]
accepted
