### ISSUE TITLE
Labels als Legende in Pie Charts

### ISSUE THREAD

**Issue by jonathankreidler** [hpi-swa-teaching/StatisticsWorkbench#90]
Als πrat möchte ich die Labels meiner Daten in einem Kreisdiagramm dargestellt bekommen. Sodass statt 1, 2, 3... die Label der Daten in der Legende stehen.

![grafik](https://user-images.githubusercontent.com/38314662/83003943-4e7d2780-a00f-11ea-9807-7261fa9598c0.png)

Aufwand: 5 h

**Comment by SanJSp** [comment]
Solves #74
